### ISSUE TITLE
Custom routes stopped working

### ISSUE THREAD

**Issue by henriquechehad** [nuveo/prest#122]
The custom routes stopped working when restrict = True

It's returning the message: `required authorization to table`

This middleware `middlewares.AccessControl` should not handle the custom URL's

**Comment by henriquechehad** [comment]
@felipeweb I think it was after this middleware refactor: https://github.com/nuveo/prest/commit/92ca666a7a28a00416702efd66925279edae06b0

**Comment by felipeweb** [comment]
yes you are right @henriquechehad

**Comment by avelino** [comment]
generate new docker image: https://hub.docker.com/r/nuveo/prest/builds/b6msbq7m3yct5nmvoaaroxb/
