### ISSUE TITLE
Authorization header : JWT or Bearer?

### ISSUE THREAD

**Issue by DudeWhoCode** [nuveo/prest#162]
The README says to use the format `JWT {token}`. When used, the server throws an error : 
```
{
  "error": "Authorization header format must be Bearer {token}"
}
```
Using `Bearer {token}` works fine.

**Comment by marioidival** [comment]
Hi @DudeWhoCode ... You are right, we use `Baerer {token}`, but this token it's JWT.

**Comment by DudeWhoCode** [comment]
Then line number 124 README.md should be changed from :
```
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
```
to 
```
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
```
Am I right?

**Comment by crgimenes** [comment]
You're right. The authentication is JWT and should be sent using the Bearer schema in the Authorization header.
We need to improve this error message.
