### ISSUE TITLE
Response is not valid when SELECTing from an empty table 

### ISSUE THREAD

**Issue by mphuie** [nuveo/prest#173]
- pREST version (or commit ref): 0.2
- pREST endpoint: /db/public/table/
- PostgreSQL version: 9.6
- Operating system: Ubuntu 14
- Go version:  (using docker container nuveo/prest:0.2)
- Log gist:

## Description

When querying a table with no rows, the API returns nothing.  This is not valid JSON.  It should return `[]`

**Comment by avelino** [comment]
@mphuie thanks report bug
