### ISSUE TITLE
BUG on Windows platform using TOML config files

### ISSUE THREAD

**Issue by khalifeserge** [nuveo/prest#179]
in config.go file the class path instead of filepath is used to parse the directory and file. This result in an empty directory on windows which uses \ as separator instead of /

changing the following line form 
`dir, file := path.Split(filePath)`
to
`dir, file := filepath.Split(filePath)`
fixes the issue since 	"path/filepath" is already imported in the beginning of the file

**Comment by marioidival** [comment]
Hi @khalifeserge, send a pull request!
