### ISSUE TITLE
go get prest/cmd and prest/config should install only these packages

### ISSUE THREAD

**Issue by lerrua** [nuveo/prest#187]
Guys,

When I do `go get -u github.com/nuveo/prest/cmd` it must download only `cmd` package, right? So, the go get command is downloading all prest files, same case when I do `go get -u github.com/nuveo/prest/config`.

**Comment by felipeweb** [comment]
@lerrua go get download all code in repository, but you can use the packages separately

**Comment by felipeweb** [comment]
@lerrua @lerrua this can be seen on https://github.com/golang/go/blob/master/src/cmd/go/internal/get/vcs.go#L501
