### ISSUE TITLE
OR filter (where)

### ISSUE THREAD

**Issue by felipeweb** [nuveo/prest#33]

**Comment by avelino** [comment]
After brainstorm we have come to the conclusion that we won't be able to implement without losing the REST feature.

To make queries with OR (or where more complex) we recommend using VIEWS (within the database) or #70 (like view the level of application)

**Comment by pastarace** [comment]
Hi any news on that with the 1.0.0 release? I know in PostgREST [OR and complex filtering is available](http://postgrest.org/en/v7.0.0/api.html#horizontal-filtering-rows)

Thanks

**Comment by avelino** [comment]
@pastarace we still don't support `complex or` operations, can you open a new issue for us to feature?

It's a resource that pREST needs to learn how to handle
