### ISSUE TITLE
JOIN feature

### ISSUE THREAD

**Issue by henriquechehad** [nuveo/prest#35]
It would be interesting to have a `JOIN` (inner, left, etc) feature?

**Comment by avelino** [comment]
**This first version accepts 1 join, then evolve to accept more.**

Syntax query:
```
/DATABASE/SCHEMA/TABLE??_join=inner:users:friends.userid:$eq:users.id
```
Parameters:

1. Join type
1. Table
1. Table field 1
1. Operator (=, <, >, <=, >=)
1. Table field 2

Split by `:`

Query Operators:

| Name | Description |
|-------|-------------|
| $eq | Matches values that are equal to a specified value.|
| $gt | Matches values that are greater than a specified value.|
| $gte | Matches values that are greater than or equal to a specified value.|
| $lt | Matches values that are less than a specified value.|
| $lte | Matches values that are less than or equal to a specified value.|
| $ne | Matches all values that are not equal to a specified value.|
| $in | Matches any of the values specified in an array.|
| $nin | Matches none of the values specified in an array.|

**Comment by henriquechehad** [comment]
👍

**Comment by henriquechehad** [comment]
PR: https://github.com/nuveo/prest/pull/54
