### ISSUE TITLE
SQL injection is possible

### ISSUE THREAD

**Issue by pixelbender** [nuveo/prest#36]
Using fmt.Sprintf from a user input data:
https://github.com/nuveo/prest/blob/master/adapters/postgres/postgres.go#L58
and then calling postgres.Query:
https://github.com/nuveo/prest/blob/master/controllers/databases.go#L25
is a very bad practice that allows to user make SQL injections.

**Comment by felipeweb** [comment]
@pixelbender  thanks for reporting. Do you want to send a pull request fixing the issue?

**Comment by crgimenes** [comment]
Hello guys, I'll take care of this problem.
Suggestions are welcome.

**Comment by avelino** [comment]
@pixelbender thanks for reporting this bug, we at @Nuveo wasn't thinking that initially because it would use the pREST in private network (no public access), we will put priority on this bug.
