### ISSUE TITLE
PANIC: Unable to connection to database: pq: password authentication failed 

### ISSUE THREAD

**Issue by hdiwan** [nuveo/prest#46]
Set the password properly (using the PG_PASS environment variable), it keeps giving me this error message.

**Comment by felipeweb** [comment]
thanks for report @hdiwan

**Comment by felipeweb** [comment]
Do you want to send a PR ? @hdiwan

**Comment by hdiwan** [comment]
I already sent a pull request for an edit in the README.md, once I figure out this problem, I'll be happy to send another

**Comment by felipeweb** [comment]
Nice, let us know if you need any help

**Comment by felipeweb** [comment]
@crgimenes  @cassiobotaro  this issue is fixed? with pool implementation?

**Comment by felipeweb** [comment]
fix in PR #56
