### ISSUE TITLE
Transaction support

### ISSUE THREAD

**Issue by crgimenes** [nuveo/prest#48]
It would be great to have transaction support.

My suggestion is to make a call to pREST requesting the start of a transaction and receive an ID. Then pass that ID on the next requisitions and finally finish with a commit or rollback.

The idea of using an ID is to solve the problem of stateless calls.

**Comment by marcosinger** [comment]
@crgimenes I like this, but what about a transaction which never receive a commit or rollback? it will ends up blocking future calls? Should it have a timeout or something?

**Comment by crgimenes** [comment]
@marcosinger Perhaps with a timeout, like a session control.
Example, if the system does not receive something in X seconds, the system does a rollback and returns an error for the next call.

**Comment by crgimenes** [comment]
Probably capturing a connection to hold a transaction will complicate somewhat the implementation of issue #22.
