### ISSUE TITLE
Access control

### ISSUE THREAD

**Issue by crgimenes** [nuveo/prest#52]
I suggest implementing a way to identify the connection and validate the user/client.
So we can allow or deny access to tables, views, etc.

Also que can define a way to set allowed access to features such as a table being "insert only", or even a field being "read-only".

**Comment by avelino** [comment]
Initial implementation on PR #66

**Comment by marioidival** [comment]
It's an idea. Maybe check permissions by middleware?

**Comment by marioidival** [comment]
@crgimenes @avelino @felipeweb

**Comment by avelino** [comment]
@marioidival is migrate to middleware

**Comment by marioidival** [comment]
@avelino got it!

**Comment by avelino** [comment]
Fixed on #66, for migration to middleware create new issue
